export const styles = {
  page: {
    minHeight: "100vh",
    background: "#0f172a",
    color: "#e5e7eb",
    padding: "24px",
    fontFamily: "Arial, sans-serif",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "16px",
    flexWrap: "wrap",
    marginBottom: "24px",
  },
  headingRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  logoBox: {
    background: "#1e293b",
    padding: "12px",
    borderRadius: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  heading: {
    margin: 0,
    fontSize: "30px",
    color: "#f8fafc",
  },
  subheading: {
    margin: "6px 0 0 0",
    color: "#94a3b8",
  },
  headerControls: {
    display: "flex",
    gap: "12px",
    flexWrap: "wrap",
    alignItems: "center",
  },
  searchBox: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    background: "#1e293b",
    border: "1px solid #334155",
    borderRadius: "10px",
    padding: "10px 12px",
    minWidth: "280px",
  },
  input: {
    background: "transparent",
    border: "none",
    outline: "none",
    color: "#e5e7eb",
    width: "100%",
  },
  button: {
    display: "flex",
    alignItems: "center",
    background: "#2563eb",
    color: "white",
    border: "none",
    borderRadius: "10px",
    padding: "10px 16px",
    cursor: "pointer",
    fontWeight: 600,
  },
  errorBox: {
    background: "#7f1d1d",
    color: "#fecaca",
    padding: "12px 14px",
    borderRadius: "10px",
    marginBottom: "20px",
  },
  grid4: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "16px",
    marginBottom: "16px",
  },
  grid2: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(420px, 1fr))",
    gap: "16px",
    marginBottom: "16px",
  },
  card: {
    background: "#111827",
    border: "1px solid #1f2937",
    borderRadius: "16px",
    padding: "18px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardTitle: {
    fontSize: "14px",
    color: "#94a3b8",
    marginBottom: "8px",
  },
  cardValue: {
    fontSize: "32px",
    fontWeight: "bold",
    color: "#f8fafc",
  },
  cardSubtitle: {
    marginTop: "6px",
    fontSize: "12px",
    color: "#64748b",
  },
  iconBox: {
    background: "#1e293b",
    padding: "12px",
    borderRadius: "14px",
    color: "#cbd5e1",
  },
  section: {
    background: "#111827",
    border: "1px solid #1f2937",
    borderRadius: "16px",
    padding: "18px",
    marginBottom: "16px",
  },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
    marginBottom: "14px",
    flexWrap: "wrap",
  },
  sectionTitle: {
    margin: 0,
    fontSize: "18px",
    color: "#f8fafc",
  },
  muted: {
    color: "#94a3b8",
    fontSize: "14px",
  },
  topRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "10px 0",
    borderBottom: "1px solid #1f2937",
  },
  topLabel: {
    color: "#e5e7eb",
    maxWidth: "75%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  badge: {
    background: "#1e293b",
    color: "#cbd5e1",
    padding: "4px 10px",
    borderRadius: "999px",
    fontSize: "12px",
    fontWeight: 600,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    textAlign: "left",
    padding: "12px",
    borderBottom: "1px solid #334155",
    color: "#94a3b8",
    fontSize: "13px",
  },
  td: {
    padding: "12px",
    borderBottom: "1px solid #1f2937",
    color: "#e5e7eb",
    fontSize: "14px",
  },
  tdMono: {
    padding: "12px",
    borderBottom: "1px solid #1f2937",
    color: "#e5e7eb",
    fontSize: "12px",
    fontFamily: "monospace",
  },
  tdPre: {
    padding: "12px",
    borderBottom: "1px solid #1f2937",
    color: "#e5e7eb",
    fontSize: "12px",
    fontFamily: "monospace",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    maxWidth: "400px",
  },
  emptyCell: {
    padding: "20px",
    textAlign: "center",
    color: "#94a3b8",
  },
  clickableRow: {
    cursor: "pointer",
  },
  detailsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "12px",
  },
  detailCard: {
    background: "#0b1220",
    border: "1px solid #1e293b",
    borderRadius: "12px",
    padding: "14px",
  },
  detailLabel: {
    color: "#94a3b8",
    fontSize: "12px",
    marginBottom: "8px",
  },
  detailValue: {
    color: "#f8fafc",
    fontSize: "14px",
    wordBreak: "break-word",
  },
  detailValueMono: {
    color: "#f8fafc",
    fontSize: "12px",
    fontFamily: "monospace",
    wordBreak: "break-word",
  },
};
